name: Github Secrets

on: 
  workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps: 
        - name: Print Secret
          run: |
              echo "MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET }}"
              echo "I_dont_exist: ${{ secrets.I_dont_exists }}"
        
        - name: Print Secret as env variable
          run: |
               echo "MY_TOP_SECRET: $MY_TOP_SECRET"
          env:
               AZURE_CREDENTIALS: ${{ secrets.MY_TOP_SECRET }}             